apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-a
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-a
  template:
    metadata:
      labels:
        app: microservice-a
    spec:
      serviceAccountName: microservice-a-sa
      containers:
        - name: microservice-a
          image: microservice-a:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: microservice-a-db-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: microservice-a-db-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: microservice-a-db-config
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: microservice-a-postgres-secret
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservice-a-postgres-secret
                  key: postgres-password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
