apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: microservices
  name: service-reader
rules:
  - apiGroups: [""]
    resources:
      - services
      - endpoints
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-services-binding
  namespace: microservices
subjects:
  - kind: ServiceAccount
    name: default
    namespace: microservices
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
