apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservice-a
  namespace: {{ .Values.namespace }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: microservice-a
  endpoints:
    - port: web
      path: /actuator/prometheus
      interval: 15s