apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-b
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: microservice-b
  template:
    metadata:
      labels:
        app: microservice-b
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: microservice-b
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: microservice-b-db-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: microservice-b-db-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: microservice-b-db-config
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: microservice-b-postgres-secret
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservice-b-postgres-secret
                  key: postgres-password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
