apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservice-b-sa
  namespace: microservices
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: microservice-b-role
  namespace: microservices
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microservice-b-rb
  namespace: microservices
subjects:
  - kind: ServiceAccount
    name: microservice-b-sa
    namespace: microservices
roleRef:
  kind: Role
  name: microservice-b-role
  apiGroup: rbac.authorization.k8s.io
