apiVersion: v1
kind: Service
metadata:
  name: microservice-b
  namespace: microservices
spec:
  type: LoadBalancer
  selector:
    app: microservice-b
  ports:
    - port: 8080
      targetPort: 8080